/**
 * Shared Strings
 * All hardcoded UI text strings centralized here for easy maintenance and future i18n.
 */
const STRINGS = {
  COMMON: {
    SEARCH_PLACEHOLDER: (entity: string) => `Search ${entity}...`,
    EXPORT_CSV: 'Export CSV',
    IMPORT: 'Import',
    SORT: 'Sort',
    FILTER_BY: 'Filter by:',
    ALL_STATUS: 'All Status',
    ALL_TYPES: 'All Types',
    EDIT: 'Edit',
    DELETE: 'Delete',
    PUBLISH: 'Publish',
    UNPUBLISH: 'Unpublish',
    SAVE_DRAFT: 'Save as Draft',
    CANCEL: 'Cancel',
    CONFIRM: 'Confirm',
    BACK_TO_LOGIN: 'Back to Login',
    FOOTER_COPYRIGHT:
      '© 2024 Vision PME (Gala Management System). All rights reserved.',
  },

  AUTH: {
    APP_TITLE: 'Admin Panel',
    APP_LOGO_ALT: 'Logo',
    LOGIN: {
      SUBTITLE: 'Sign in to manage your platform',
      EMAIL_LABEL: 'Email Address',
      EMAIL_PLACEHOLDER: 'admin@example.com',
      PASSWORD_LABEL: 'Password',
      PASSWORD_PLACEHOLDER: '••••••••',
      SHOW_PASSWORD_ARIA: 'Show password',
      HIDE_PASSWORD_ARIA: 'Hide password',
      REMEMBER_ME: 'Remember me',
      FORGOT_PASSWORD: 'Forgot Password?',
      SUBMIT: 'Sign In',
    },
    FORGOT_PASSWORD: {
      TITLE: 'Forgot Password?',
      SUBTITLE: "No worries, we'll send you reset instructions",
      EMAIL_LABEL: 'Email Address',
      EMAIL_PLACEHOLDER: 'Enter your email address',
      ALERT_TITLE: 'Email Recovery',
      ALERT_TEXT:
        "Enter the email address associated with your admin account and we'll send you a link to reset your password.",
      SUBMIT: 'Send Reset Link',
    },
    EMAIL_SENT: {
      TITLE: 'Check Your Email',
      SUBTITLE: "We've sent password reset instructions",
      EMAIL_SENT_LABEL: 'Email Sent To:',
      EMAIL_SENT_VALUE: 'admin@example.com',
      STEP_1: 'Check your email inbox for the reset link',
      STEP_2: 'Click on the link to reset your password',
      STEP_3: 'Create a new secure password',
      ALERT_TITLE: 'Link Expires Soon',
      ALERT_TEXT:
        'The password reset link will expire in 1 hour for security purposes.',
      OPEN_EMAIL: 'Open Email App',
      RESEND: 'Resend Email',
      SPAM_NOTE: "Didn't receive the email? Check your spam folder",
    },
    RESET_PASSWORD: {
      TITLE: 'Set New Password',
      SUBTITLE: 'Choose a strong password for your account',
      NEW_PASS_LABEL: 'New Password',
      NEW_PASS_PLACEHOLDER: 'Enter new password',
      CONFIRM_PASS_LABEL: 'Confirm Password',
      CONFIRM_PASS_PLACEHOLDER: 'Confirm new password',
      SUBMIT: 'Reset Password',
    },
    RESET_SUCCESS: {
      TITLE: 'Password Reset Successful!',
      SUBTITLE: 'Your password has been successfully reset',
      ALERT_TITLE: 'Secure Password Set',
      ALERT_TEXT:
        'Your new password meets all security requirements and has been saved successfully.',
      WHATS_NEXT: "What's Next?",
      NEXT_1_HEADING: 'Sign in with your new password',
      NEXT_1_DESC: 'Use your updated credentials to access the admin panel',
      NEXT_2_HEADING: 'Keep your password secure',
      NEXT_2_DESC: "Don't share your password with anyone",
      SUBMIT: 'Continue to Login',
    },
  },

  DASHBOARD: {
    TITLE: 'Dashboard Overview',
    SUBTITLE: "Welcome back! Here's what's happening today",
    SETTINGS_BTN: 'Settings',
    CHART_USERS_TITLE: 'Monthly New Users',
    CHART_USERS_SUBTITLE: 'New user registrations per month',
    CHART_USERS_LABEL: 'Users',
    CHART_UNSUB_TITLE: 'Monthly Unsubscriptions',
    CHART_UNSUB_SUBTITLE: 'Users who cancelled their subscription',
    CHART_UNSUB_LABEL: 'Unsubscriptions',
    KPI: {
      TOTAL_USERS: 'Total Users',
      ACTIVE_GALAS: 'Active Galas',
      MONTHLY_REVENUE: 'Monthly Revenue',
      APPLICATIONS: 'Applications',
      APP_DOWNLOADS: 'App Downloads',
      ACTIVE_GRANTS: 'Active Grants',
      PASSPORT_KPI: 'Passport KPI',
      PASSPORT_MONTHLY_SUB: 'Active passports this month',
      PASSPORT_YEARLY_SUB: 'Total passports this year',
      PERIOD_MONTHLY: 'Monthly',
      PERIOD_YEARLY: 'Yearly',
    },
  },

  APPLICATIONS: {
    TITLE: 'Application Management',
    SUBTITLE: 'Review and manage all submitted applications',
    SEARCH_PLACEHOLDER: 'Search applications...',
    EXPORT_CSV: 'Export CSV',
    FILTER_ALL_GALAS: 'All Galas',
    FILTER_ALL_GRANTS: 'All Grants',
    FILTER_ALL_CLASSES: 'All Classes',
    FILTER_RATING: 'Rating: Best First',
    TABS: ['All', 'Pending', 'Approved', 'Rejected', 'Past Events'],
    TABLE: {
      APPLICANT: 'Applicant',
      GALA_NAME: 'Gala Name',
      GRANT: 'Grant',
      APPLIED_DATE: 'Applied Date',
      JURY_SCORE: 'Jury Score',
      STATUS: 'Status',
      ACTIONS: 'Actions',
    },
    APPROVE: 'Approve',
    REJECT: 'Reject',
  },

  USERS: {
    TITLE: 'User Management',
    SUBTITLE: 'View and manage all registered users',
    KPI_TOTAL_USERS: 'Total Users',
    KPI_ACTIVE_SUBS: 'Active Subscriptions',
    KPI_MEMBERS: 'Members (No Passport)',
    KPI_BLOCKED: 'Blocked Users',
    SEARCH_PLACEHOLDER: 'Search users...',
    IMPORT_USERS: 'Import Users',
    EXPORT_USERS: 'Export Users',
    CREATE_USER: 'Create New User',
    TABS: [
      'All',
      'Active',
      'Passport',
      'Member',
      'Blocked',
      'Trial',
      'Trial Expired',
    ],
    PAGINATION_INFO: (from: number, to: number, total: string) =>
      `Showing ${from}-${to} of ${total} users`,
    SUBSCRIPTION_LEGEND_LABEL: 'Subscription Types:',
    LEGEND: {
      MONTHLY: 'Monthly',
      MONTHLY_DESC: '= Passport (Premium)',
      YEARLY: 'Yearly',
      YEARLY_DESC: '= Passport (Premium)',
      MEMBER: 'Member',
      MEMBER_DESC: '= Regular paying user',
      TRIAL: 'Trial',
      TRIAL_DESC: '= Free trial',
    },
    TABLE: {
      USER: 'User',
      EMAIL: 'Email',
      SUBSCRIPTION: 'Subscription',
      JOINED_DATE: 'Joined Date',
      STATUS: 'Status',
      ACTIONS: 'Actions',
    },
    BLOCK: 'Block',
    UNBLOCK: 'Unblock',
  },

  GALAS: {
    TITLE: 'Gala Management',
    SUBTITLE: 'Manage and announce your gala events',
    SEARCH_PLACEHOLDER: 'Search galas...',
    CREATE_BTN: '+ Create New Gala',
    APPLIED_SUFFIX: 'Applied',
    PUBLISH: 'Publish',
    UNPUBLISH: 'Unpublish',
    DELETE: 'Delete',
    EDIT: 'Edit',
  },

  GRANTS: {
    TITLE: 'Grant Management',
    SUBTITLE: 'Create and manage grant programs',
    SEARCH_PLACEHOLDER: 'Search grants...',
    ADD_BTN: 'Add New Grant',
    ADD_PLACEHOLDER_HEADING: 'Add New Grant',
    ADD_PLACEHOLDER_BODY: 'Create a new Grant program',
    KPI: {
      TOTAL_GRANTS: 'Total Grants',
      ACTIVE_PROGRAMS: 'Active Programs',
      TOTAL_FUND: 'Total Fund Amount',
      TOTAL_APPLICANTS: 'Total Applicants',
    },
    META: {
      AWARD_AMOUNT: 'Award Amount',
      DEADLINE: 'Deadline',
      APPLICANTS: 'Applicants',
    },
    ELIGIBILITY_TITLE: 'Eligibility Criteria',
    REOPEN: 'Reopen',
    PERIOD: 'Since last month',
  },

  ANNOUNCEMENTS: {
    TITLE: 'Announcements & Notifications',
    SUBTITLE: 'Create and manage platform announcements',
    CREATE_CARD_TITLE: 'Create Announcement',
    CREATE_CARD_SUBTITLE: 'Publish a new announcement or notification',
    FORM: {
      TITLE_LABEL: 'Title',
      TITLE_PLACEHOLDER: 'Enter announcement title...',
      MESSAGE_LABEL: 'Message',
      MESSAGE_PLACEHOLDER: 'Write your announcement message here...',
      AUDIENCE_LABEL: 'Target Audience',
      AUDIENCE_ALL: 'All Users',
      AUDIENCE_ADMINS: 'Admins Only',
      AUDIENCE_JURY: 'Jury Members',
      SCHEDULE_LABEL: 'Schedule',
      SCHEDULE_TOGGLE_ARIA: 'Toggle scheduled announcement',
      SCHEDULE_DATE_PLACEHOLDER: 'Select date and time',
      PUSH_NOTIFICATION: 'Send push notification to users',
      PUBLISH_NOW: 'Publish Now',
      SAVE_DRAFT: 'Save as Draft',
    },
    LIST_TITLE: 'Recent Announcements',
    TABS: ['All', 'Published', 'Draft'],
    VIEWS_SUFFIX: 'views',
  },

  ADMINS: {
    TITLE: 'Admin Management',
    SEARCH_PLACEHOLDER: 'Search admins...',
    ALL_ROLES: 'All Roles',
    CREATE_BTN: '+ Create New Admin',
    TABLE: {
      ADMIN: 'Admin',
      ROLE: 'Role',
      LAST_ACTIVE: 'Last Active',
      STATUS: 'Status',
      ACTIONS: 'Actions',
    },
  },
};

export default STRINGS;
